image: gradle:latest

stages:
  - sample-stage
  - test
  - jacoco-coverage

test:
  stage: test
  script: 
    - gradlew test

jacoco-coverage:
  stage: jacoco-coverage
  script:
    - gradlew jacocoTestCoverageVerification

checkstyle:
  stage: checkstyle
  script:
    - gradlew check