image: gradle:latest

stages:
  - build
  - test
  - jacoco-coverage
  - checkstyle

build:
  stage: build
  script:
  - echo "$CI_MERGE_REQUEST_DIFF_ID"
  - gradle assemble

test:
  stage: test
  script:
    - gradle test
    - gradle testCodeCoverageReport
    - cat $CI_PROJECT_DIR/build/reports/jacoco/testCodeCoverageReport/html/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Code Coverage:/'
  artifacts:
    paths:
    - $CI_PROJECT_DIR/domain/build/reports/*

jacoco-coverage:
  stage: jacoco-coverage
  script:
    - gradle jacocoTestCoverageVerification
  artifacts:
    paths:
    - $CI_PROJECT_DIR/domain/build/reports/*

checkstyle:
  stage: checkstyle
  script:
    - gradle check
  artifacts:
    paths:
    - $CI_PROJECT_DIR/domain/build/reports/*
